### ISSUE TITLE
E404 with font-awesome

### ISSUE THREAD

**Issue by nitroplonker** [BhavinPatel04/ngx-datetime-range-picker#12]
I am trying out your date picker and running into an error with regards to font-awesome.

I am getting the below error even though i have fontawesome loading into the app correctly through the angular.json assets.

http://localhost:4200/~font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 

Any ideas?

many thanks

**Comment by BhavinPatel04** [comment]
Can you please paste the exact error?

I'm assuming you installed `font-awesome` in your application. Can I take a look at your app or angular.json?

**Comment by assafWifiWall** [comment]
Same here:

`ERROR in ./src/app/@theme/styles/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--13-3!./src/app/@theme/styles/styles.scss)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: <full_path>/node_modules/ngx-datetime-range-picker/ngx-datetime-range-picker.theme.scss:13728:4: Can't resolve 'font-awesome/fonts/fontawesome-webfont.svg' in '/<full_path>/src/app/@theme/styles'`

`
  13726 |     url('#{$fa-font-path}/fontawesome-webfont.woff?v=#{$fa-version}') format('woff'),
  13727 |     url('#{$fa-font-path}/fontawesome-webfont.ttf?v=#{$fa-version}') format('truetype'),
> 13728 |     url('#{$fa-font-path}/fontawesome-webfont.svg?v=#{$fa-version}#fontawesomeregular') format('svg');
        |    ^
  13729 | //  src: url('#{$fa-font-path}/FontAwesome.otf') format('opentype'); // used when developing fonts
  13730 |   font-weight: normal;

`

Running Angular 8.x
Here is my dependencies list:

`"dependencies": {
    "@agm/core": "^1.0.0",
    "@angular/animations": "^8.2.13",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^8.2.13",
    "@angular/compiler": "^8.2.13",
    "@angular/core": "^8.2.13",
    "@angular/forms": "^8.2.13",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "^8.2.13",
    "@angular/platform-browser-dynamic": "^8.2.13",
    "@angular/router": "^8.2.13",
    "@asymmetrik/ngx-leaflet": "3.0.1",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@nebular/auth": "4.1.2",
    "@nebular/eva-icons": "^4.5.0",
    "@nebular/moment": "^4.5.0",
    "@nebular/security": "4.1.2",
    "@nebular/theme": "4.1.2",
    "@sweetalert2/ngx-sweetalert2": "^6.0.1",
    "@swimlane/ngx-charts": "^10.1.0",
    "ag-grid-angular": "^21.2.2",
    "ag-grid-community": "^21.2.2",
    "angular-tree-component": "7.2.0",
    "angular2-chartjs": "0.4.1",
    "angular2-toaster": "^7.0.0",
    "bootstrap": "4.3.1",
    "chart.js": "^2.9.2",
    "ckeditor": "4.7.3",
    "classlist.js": "1.1.20150312",
    "core-js": "2.5.1",
    "echarts": "^4.4.0",
    "echarts-gl": "^1.1.1",
    "eva-icons": "^1.1.2",
    "intl": "1.2.5",
    "ionicons": "2.0.1",
    "leaflet": "1.2.0",
    "moment": "^2.24.0",
    "nebular-icons": "1.1.0",
    "ng2-ckeditor": "^1.2.6",
    "ng2-completer": "2.0.8",
    "ng2-smart-table": "1.3.5",
    "ngx-awesome-uploader": "^8.0.3",
    "ngx-datetime-range-picker": "^2.0.0",
    "ngx-echarts": "^4.2.2",
    "node-sass": "^4.13.0",
    "normalize.css": "6.0.0",
    "pace-js": "1.0.2",
    "roboto-fontface": "0.8.0",
    "rxjs": "6.5.2",
    "rxjs-compat": "6.3.0",
    "socicon": "3.0.5",
    "sweetalert2": "^8.19.0",
    "tinymce": "4.5.7",
    "tslib": "^1.10.0",
    "typeface-exo": "0.0.22",
    "web-animations-js": "github:angular/web-animations-js#release_pr208",
    "zone.js": "~0.9.1"
  }`

Would appreciate any help.

**Comment by BhavinPatel04** [comment]
@nitroplonker and @assafWifiWall, can you guys try specifying the font path before importing font-awesome css like below?
````
$fa-font-path: "~font-awesome/fonts";
@import "~font-awesome/scss/font-awesome.scss";
````

**Comment by BhavinPatel04** [comment]
Closing it due to inactivity. Please feel free to reopen if you guys are still facing this issue.
