### ISSUE TITLE
Still having issue of :: Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module

### ISSUE THREAD

**Issue by neheartRock** [BhavinPatel04/ngx-datetime-range-picker#7]
I'm having **BrowserModule and BrowserAnimation module in my main app.module**,
and in my LazyLoaded module, I import NgxDatetimeRangePickerModule, 
so this error is there..

Any Solution for this?

**Comment by BhavinPatel04** [comment]
This is not an issue with ngx-datetime-range-picker. Latest verion of ngx-datetime-range-picker [1.1.3] does NOT import BrowserModule & BrowserAnimaionModule.

This seems to be an issue with your LazyLoaded module. BrowserModule and BrowserAnimationsModule should only be imported once in your application.

You can use the below in your LazyModule instead:
`import { NoopAnimationsModule } from "@angular/platform-browser/animations";`

**Comment by gieseking** [comment]
I'm still receiving this issue with version 1.1.5. I am only importing BrowserModule and BrowserAnimationsModule once in my app.module. Is there any resolution to this?

**Comment by BhavinPatel04** [comment]
@gieseking As I mentioned, the library is not at all importing BrowserModule or BrowserAnimationModule. Can you please check if any other library is importing those? 
It would be also helpful to debug if you paste your error :)

**Comment by gieseking** [comment]
@BhavinPatel04 Thanks for the effort on this component. It looks promising and I look forward to being able to use it. I've pasted the error below. As soon as I remove NgxDatetimeRangePickerModule from Imports the error goes away.

Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.↵Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.↵    at new BrowserModule (https://localhost:4200/vendor.js:87650:19)↵    at _createClass (https://localhost:4200/vendor.js:74564:20)↵    at _createProviderInstance (https://localhost:4200/vendor.js:74536:26)↵    at initNgModule (https://localhost:4200/vendor.js:74469:32)↵    at new NgModuleRef_ (https://localhost:4200/vendor.js:75196:9)↵    at createNgModuleRef (https://localhost:4200/vendor.js:75185:12)↵    at Object.debugCreateNgModuleRef [as createNgModuleRef] (https://localhost:4200/vendor.js:77016:12)↵    at NgModuleFactory_.push../node_modules/@angular/core/fesm5/core.js.NgModuleFactory_.create (https://localhost:4200/vendor.js:77744:25)↵    at MapSubscriber.project (https://localhost:4200/vendor.js:91862:34)↵    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (https://localhost:4200/vendor.js:269419:35)"

**Comment by gieseking** [comment]
The problem I was encountering was due to importing the module on a child module of app.module (ThemeModulee), which was required for me to be able to use it in pages that imported themeModule but not AppModule. It seems there are problems importing NoopAnimationsModule in any component other than the root module alongside BrowserModule and BrowserAnimationsModule. In order to get this to work I had to clone the repo and remove the import of NoopAnimationsModule. I then added an Import to NoopAnimationsModule in my AppModule.

**Comment by BhavinPatel04** [comment]
@gieseking Glad to know that your issue is resolved. 

After little bit of thinking I realized I don't need to import `NoopAnimationsModule` at all in the library and the library works fine until you import BrowserModule and BrowserAnimationModule in your root module (AppModule). 

I've removed NoopAnimationsModule and you can import the latest version `1.1.7` and use it as is 😃 

Although, I don't think you need to import NoopAnimationsModule alongside BrowserModule and BrowserAnimationsModule.
